# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('pmtType', models.CharField(choices=[('F', 'FIXED'), ('GA', 'GIVE_AWAY'), ('C', 'CONTACT'), ('ST', 'SWAP_TRADE')], max_length=2)),
                ('priceType', models.CharField(choices=[('F', 'FIXED'), ('GA', 'GIVE_AWAY'), ('C', 'CONTACT'), ('ST', 'SWAP_TRADE')], max_length=2)),
                ('attr0', models.CharField(default='forsaleby_s,ownr', max_length=500)),
                ('attr1', models.CharField(default='', max_length=500)),
                ('attr2', models.CharField(default='', max_length=500)),
                ('priceAmount', models.IntegerField()),
                ('locationId', models.CharField(default='1700212', max_length=20)),
            ],
        ),
    ]
