# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_auto_20161222_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postableattr',
            unique_together=set([('related_item', 'key')]),
        ),
    ]
