# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0007_auto_20161222_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='postableitem',
            name='categoryId',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
