# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_postableitem_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='postableitem',
            name='photo10',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo7',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo8',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AddField(
            model_name='postableitem',
            name='photo9',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
        migrations.AlterField(
            model_name='postableitem',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='postable_item_photos'),
        ),
    ]
